---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  scss-lint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
    - 250e70f47bf1b3f8f935bdaf6e4fe235
    - 68339ea563bea69f39fc8b4ddeb6615c
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- config/
- db/
- spec/
- vendor/
- coverage/
